### ISSUE TITLE
feat: Initialize project files

### ISSUE THREAD

**Issue by MarJaysonSanAgustin** [MarJaysonSanAgustin/notes-app#1]
## 📃 Description

Generate initial folder and file structure using the vue-cli

## 📋 Todo
- [ ] Install vue-cli on local dev environment
- [ ] Generate initial files and folders using the cli
- [ ] Push to the repo
