### ISSUE TITLE
cleanup: remove unused files

### ISSUE THREAD

**Issue by MarJaysonSanAgustin** [MarJaysonSanAgustin/notes-app#3]
## 📄 Description

Remove initially generated files.

## 📋 Todo

- [x] - Remove About.vue
- [x] - Remove Home.vue
- [x] - Remove HomeComponent.vue
- [x] - Update router - Remove Home.vue
- [x] - Update router - Remove Home.vue
